name: pokedex
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  cupertino_icons: ^1.0.2
  http: ^0.13.2
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - 1.svg
    - 2.svg 
    - 3.svg 
    - 4.svg 
    - 5.svg 
    - 6.svg 
    - 7.svg 
    - 8.svg 
    - 9.svg 
    - 10.svg
    - 11.svg
    - 12.svg
    - 13.svg
    - 14.svg
    - 15.svg
    - 16.svg
    - 17.svg
    - 18.svg
    - 19.svg
    - 20.svg
    - 21.svg
    - 22.svg
    - 23.svg
    - 24.svg
    - 25.svg
    - 26.svg
    - 27.svg
    - 28.svg
    - 29.svg
    - 30.svg
    - 31.svg
    - 32.svg
    - 33.svg
    - 34.svg
    - 35.svg
    - 36.svg
    - 37.svg
    - 38.svg
    - 39.svg
    - 40.svg
    - 41.svg
    - 42.svg
    - 43.svg
    - 44.svg
    - 45.svg
    - 46.svg
    - 47.svg
    - 48.svg
    - 49.svg
    - 50.svg
    - 51.svg
    - 52.svg
    - 53.svg
    - 54.svg
    - 55.svg
    - 56.svg
    - 57.svg
    - 58.svg
    - 59.svg
    - 60.svg
    - 61.svg
    - 62.svg
    - 63.svg
    - 64.svg
    - 65.svg
    - 66.svg
    - 67.svg
    - 68.svg
    - 69.svg
    - 70.svg
    - 71.svg
    - 72.svg
    - 73.svg
    - 74.svg
    - 75.svg
    - 76.svg
    - 77.svg
    - 78.svg
    - 79.svg
    - 80.svg
    - 81.svg
    - 82.svg
    - 83.svg
    - 84.svg
    - 85.svg
    - 86.svg
    - 87.svg
    - 88.svg
    - 89.svg
    - 90.svg
    - 91.svg
    - 92.svg
    - 93.svg
    - 94.svg
    - 95.svg
    - 96.svg
    - 97.svg
    - 98.svg
    - 99.svg
    - 100.svg
    - 101.svg
    - 102.svg
    - 103.svg
    - 104.svg
    - 105.svg
    - 106.svg
    - 107.svg
    - 108.svg
    - 109.svg
    - 110.svg
    - 111.svg
    - 112.svg
    - 113.svg
    - 114.svg
    - 115.svg
    - 116.svg
    - 117.svg
    - 118.svg
    - 119.svg
    - 120.svg
    - 121.svg
    - 122.svg
    - 123.svg
    - 124.svg
    - 125.svg
    - 126.svg
    - 127.svg
    - 128.svg
    - 129.svg
    - 130.svg
    - 131.svg
    - 132.svg
    - 133.svg
    - 134.svg
    - 135.svg
    - 136.svg
    - 137.svg
    - 138.svg
    - 139.svg
    - 140.svg
    - 141.svg
    - 142.svg
    - 143.svg
    - 144.svg
    - 145.svg
    - 146.svg
    - 147.svg
    - 148.svg
    - 149.svg
    - 150.svg
    - 151.svg
    - 152.svg
    - 153.svg
    - 154.svg
    - 155.svg
    - 156.svg
    - 157.svg
    - 158.svg
    - 159.svg
    - 160.svg
    - 161.svg
    - 162.svg
    - 163.svg
    - 164.svg
    - 165.svg
    - 166.svg
    - 167.svg
    - 168.svg
    - 169.svg
    - 170.svg
    - 171.svg
    - 172.svg
    - 173.svg
    - 174.svg
    - 175.svg
    - 176.svg
    - 177.svg
    - 178.svg
    - 179.svg
    - 180.svg
    - 181.svg
    - 182.svg
    - 183.svg
    - 184.svg
    - 185.svg
    - 186.svg
    - 187.svg
    - 188.svg
    - 189.svg
    - 190.svg
    - 191.svg
    - 192.svg
    - 193.svg
    - 194.svg
    - 195.svg
    - 196.svg
    - 197.svg
    - 198.svg
    - 199.svg
    - 200.svg
    - 201.svg
    - 202.svg
    - 203.svg
    - 204.svg
    - 205.svg
    - 206.svg
    - 207.svg
    - 208.svg
    - 209.svg
    - 210.svg
    - 211.svg
    - 212.svg
    - 213.svg
    - 214.svg
    - 215.svg
    - 216.svg
    - 217.svg
    - 218.svg
    - 219.svg
    - 220.svg
    - 221.svg
    - 222.svg
    - 223.svg
    - 224.svg
    - 225.svg
    - 226.svg
    - 227.svg
    - 228.svg
    - 229.svg
    - 230.svg
    - 231.svg
    - 232.svg
    - 233.svg
    - 234.svg
    - 235.svg
    - 236.svg
    - 237.svg
    - 238.svg
    - 239.svg
    - 240.svg
    - 241.svg
    - 242.svg
    - 243.svg
    - 244.svg
    - 245.svg
    - 246.svg
    - 247.svg
    - 248.svg
    - 249.svg
    - 250.svg
    - 251.svg
    - 252.svg
    - 253.svg
    - 254.svg
    - 255.svg
    - 256.svg
    - 257.svg
    - 258.svg
    - 259.svg
    - 260.svg
    - 261.svg
    - 262.svg
    - 263.svg
    - 264.svg
    - 265.svg
    - 266.svg
    - 267.svg
    - 268.svg
    - 269.svg
    - 270.svg
    - 271.svg
    - 272.svg
    - 273.svg
    - 274.svg
    - 275.svg
    - 276.svg
    - 277.svg
    - 278.svg
    - 279.svg
    - 280.svg
    - 281.svg
    - 282.svg
    - 283.svg
    - 284.svg
    - 285.svg
    - 286.svg
    - 287.svg
    - 288.svg
    - 289.svg
    - 290.svg
    - 291.svg
    - 292.svg
    - 293.svg
    - 294.svg
    - 295.svg
    - 296.svg
    - 297.svg
    - 298.svg
    - 299.svg
    - 300.svg
    - 301.svg
    - 302.svg
    - 303.svg
    - 304.svg
    - 305.svg
    - 306.svg
    - 307.svg
    - 308.svg
    - 309.svg
    - 310.svg
    - 311.svg
    - 312.svg
    - 313.svg
    - 314.svg
    - 315.svg
    - 316.svg
    - 317.svg
    - 318.svg
    - 319.svg
    - 320.svg
    - 321.svg
    - 322.svg
    - 323.svg
    - 324.svg
    - 325.svg
    - 326.svg
    - 327.svg
    - 328.svg
    - 329.svg
    - 330.svg
    - 331.svg
    - 332.svg
    - 333.svg
    - 334.svg
    - 335.svg
    - 336.svg
    - 337.svg
    - 338.svg
    - 339.svg
    - 340.svg
    - 341.svg
    - 342.svg
    - 343.svg
    - 344.svg
    - 345.svg
    - 346.svg
    - 347.svg
    - 348.svg
    - 349.svg
    - 350.svg
    - 351.svg
    - 352.svg
    - 353.svg
    - 354.svg
    - 355.svg
    - 356.svg
    - 357.svg
    - 358.svg
    - 359.svg
    - 360.svg
    - 361.svg
    - 362.svg
    - 363.svg
    - 364.svg
    - 365.svg
    - 366.svg
    - 367.svg
    - 368.svg
    - 369.svg
    - 370.svg
    - 371.svg
    - 372.svg
    - 373.svg
    - 374.svg
    - 375.svg
    - 376.svg
    - 377.svg
    - 378.svg
    - 379.svg
    - 380.svg
    - 381.svg
    - 382.svg
    - 383.svg
    - 384.svg
    - 385.svg
    - 386.svg
    - 387.svg
    - 388.svg
    - 389.svg
    - 390.svg
    - 391.svg
    - 392.svg
    - 393.svg
    - 394.svg
    - 395.svg
    - 396.svg
    - 397.svg
    - 398.svg
    - 399.svg
    - 400.svg
    - 401.svg
    - 402.svg
    - 403.svg
    - 404.svg
    - 405.svg
    - 406.svg
    - 407.svg
    - 408.svg
    - 409.svg
    - 410.svg
    - 411.svg
    - 412.svg
    - 413.svg
    - 414.svg
    - 415.svg
    - 416.svg
    - 417.svg
    - 418.svg
    - 419.svg
    - 420.svg
    - 421.svg
    - 422.svg
    - 423.svg
    - 424.svg
    - 425.svg
    - 426.svg
    - 427.svg
    - 428.svg
    - 429.svg
    - 430.svg
    - 431.svg
    - 432.svg
    - 433.svg
    - 434.svg
    - 435.svg
    - 436.svg
    - 437.svg
    - 438.svg
    - 439.svg
    - 440.svg
    - 441.svg
    - 442.svg
    - 443.svg
    - 444.svg
    - 445.svg
    - 446.svg
    - 447.svg
    - 448.svg
    - 449.svg
    - 450.svg
    - 451.svg
    - 452.svg
    - 453.svg
    - 454.svg
    - 455.svg
    - 456.svg
    - 457.svg
    - 458.svg
    - 459.svg
    - 460.svg
    - 461.svg
    - 462.svg
    - 463.svg
    - 464.svg
    - 465.svg
    - 466.svg
    - 467.svg
    - 468.svg
    - 469.svg
    - 470.svg
    - 471.svg
    - 472.svg
    - 473.svg
    - 474.svg
    - 475.svg
    - 476.svg
    - 477.svg
    - 478.svg
    - 479.svg
    - 480.svg
    - 481.svg
    - 482.svg
    - 483.svg
    - 484.svg
    - 485.svg
    - 486.svg
    - 487.svg
    - 488.svg
    - 489.svg
    - 490.svg
    - 491.svg
    - 492.svg
    - 493.svg
    - 494.svg
    - 495.svg
    - 496.svg
    - 497.svg
    - 498.svg
    - 499.svg
    - 500.svg
    - 501.svg
    - 502.svg
    - 503.svg
    - 504.svg
    - 505.svg
    - 506.svg
    - 507.svg
    - 508.svg
    - 509.svg
    - 510.svg
    - 511.svg
    - 512.svg
    - 513.svg
    - 514.svg
    - 515.svg
    - 516.svg
    - 517.svg
    - 518.svg
    - 519.svg
    - 520.svg
    - 521.svg
    - 522.svg
    - 523.svg
    - 524.svg
    - 525.svg
    - 526.svg
    - 527.svg
    - 528.svg
    - 529.svg
    - 530.svg
    - 531.svg
    - 532.svg
    - 533.svg
    - 534.svg
    - 535.svg
    - 536.svg
    - 537.svg
    - 538.svg
    - 539.svg
    - 540.svg
    - 541.svg
    - 542.svg
    - 543.svg
    - 544.svg
    - 545.svg
    - 546.svg
    - 547.svg
    - 548.svg
    - 549.svg
    - 550.svg
    - 551.svg
    - 552.svg
    - 553.svg
    - 554.svg
    - 555.svg
    - 556.svg
    - 557.svg
    - 558.svg
    - 559.svg
    - 560.svg
    - 561.svg
    - 562.svg
    - 563.svg
    - 564.svg
    - 565.svg
    - 566.svg
    - 567.svg
    - 568.svg
    - 569.svg
    - 570.svg
    - 571.svg
    - 572.svg
    - 573.svg
    - 574.svg
    - 575.svg
    - 576.svg
    - 577.svg
    - 578.svg
    - 579.svg
    - 580.svg
    - 581.svg
    - 582.svg
    - 583.svg
    - 584.svg
    - 585.svg
    - 586.svg
    - 587.svg
    - 588.svg
    - 589.svg
    - 590.svg
    - 591.svg
    - 592.svg
    - 593.svg
    - 594.svg
    - 595.svg
    - 596.svg
    - 597.svg
    - 598.svg
    - 599.svg
    - 600.svg
    - 601.svg
    - 602.svg
    - 603.svg
    - 604.svg
    - 605.svg
    - 606.svg
    - 607.svg
    - 608.svg
    - 609.svg
    - 610.svg
    - 611.svg
    - 612.svg
    - 613.svg
    - 614.svg
    - 615.svg
    - 616.svg
    - 617.svg
    - 618.svg
    - 619.svg
    - 620.svg
    - 621.svg
    - 622.svg
    - 623.svg
    - 624.svg
    - 625.svg
    - 626.svg
    - 627.svg
    - 628.svg
    - 629.svg
    - 630.svg
    - 631.svg
    - 632.svg
    - 633.svg
    - 634.svg
    - 635.svg
    - 636.svg
    - 637.svg
    - 638.svg
    - 639.svg
    - 640.svg
    - 641.svg
    - 642.svg
    - 643.svg
    - 644.svg
    - 645.svg
    - 646.svg
    - 647.svg
    - 648.svg
    - 649.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
